fashionista/cool/urls.py
from django.conf.urls import url
from  . import views


app_name = 'cool'
urlpatterns = [
    # / cool app root directory
    url(r'^$', views.index, name= 'index'),

    # / cool app root directory
    url(r'^yo/$', views.yo, name= 'yo'),

    # /cool/register/
    url(r'register/$', views.AccountsCreate.as_view(), name= 'register'),

    # /cool/login/
    url(r'login/$', views.UserFormView.as_view(), name= 'login'),

    # /cool/logout/
    url(r'logout/$', views.logout_user, name='logout'),

    # /cool/mypage/2
    url(r'mypage/(?P<user_id>[0-9]+)/$', views.mypage, name= 'mypage'),



    #    /cool/mypage/2
    url(r'voting/$', views.voting, name= 'voting'),

    # /cool/mypage/2
    url(r'profile/$', views.profile, name= 'profile'),



]

fashionista/fashionista/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # / index path of website is in cool app URLconfig
    url(r'^cool/', include('cool.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fashionista/cool/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.

class Accounts(models.Model):
    userid = models.IntegerField(default=0)
    name = models.CharField(max_length=300, default='')
    mobile = models.CharField(max_length=20, default='')
    photo = models.FileField(null=True)
    additional_info = models.CharField(max_length=2000, default='')
    contest_pic = models.FileField(null=True)
    likes_count = models.IntegerField(default=0)


    def get_absolute_url(self):
        return reverse('cool:index')


    def __str__(self):
        return self.name + ' - ' + self.mobile

class Likes(models.Model):
    likers_id = models.IntegerField()
    pic_id  = models.IntegerField()
    created_at = models.DateTimeField()

    def __str__(self):
        return self.likers_id

fashionista/cool/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Accounts


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Accounts
        fields = ['name', 'mobile', 'photo', 'additional_info', 'contest_pic',]

fashionista/cool/views.py
from django.shortcuts import render
from django.http import HttpResponse
# using generic view
from django.views import generic
from django.http import HttpResponse
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.core.urlresolvers import reverse_lazy
from .forms import UserForm
from django.views.generic import View
from .models import Accounts
from .forms import ProfileForm


def index(request):
    return render(request, 'cool/index.html')

def yo(request):
    return render(request, 'cool/index.html')

def mypage(request, user_id):
    return render(request, 'cool/mypage.html', {'user_id': user_id} )


def voting(request):
    return render(request, 'cool/mypage.html',  )

def profile(request):
    return render(request, 'cool/mypage.html',  )

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'cool/index.html', context)

# create Accounts object
class AccountsCreate(CreateView):
    model = Accounts
    fields = ['name', 'mobile', 'photo', 'additional_info', 'contest_pic',]



# Login
class UserFormView(View):
    form_class = UserForm
    template_name = 'cool/accounts_form.html'

    # New user coming to the site, send him blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # form data processing
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned and normalize data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user.set_password(password)
            user.save()
            # registration complete

            # Login and redirect

            user = authenticate(username = username, password = password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('cool:mypage')

        return render(request, self.template_name, {'form': form})

fashionista/cool/templates/cool/accounts_form.html
{% extends 'cool/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'cool/registration_form.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="#">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


fashionista/cool/templates/cool/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'cool/styles.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>


</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'cool:index' %}">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'cool:register' %}">Sign Up</a></li>
        <li><a href="#">Login</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% block body %}
{% endblock %}

</body>
</html>

fashionista/cool/templates/cool/index.html
{% extends 'cool/base.html' %}
{% block title %}Brand{% endblock %}

{% block body %}
{% endblock %}

fashionista/cool/templates/cool/login.html
{% extends 'cool/base.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'cool:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


fashionista/cool/templates/cool/login_form.html
{% extends 'cool/base.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'cool/registration_form.html' %}
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="#">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


fashionista/cool/templates/cool/mypage.html
{% extends 'cool/base.html' %}
{% block title %}My Page{% endblock %}

{% block body %}
    {% load staticfiles %}
    <div class="row text-center" style="margin: 0 auto;">

    <div class="col-md-5"  style="margin: 15px;border: 1px solid cornflowerblue;height: 500px;">
        <a href="#" class="btn btn-success">Voting Time</a>
        <img src="{% static 'cool/image/vote11.jpg' %}">
    </div>
    <div class="col-md-5"  style="margin: 15px;border: 1px solid cornflowerblue;height: 500px;">
        <a href="{% url 'cool:register' %}" class="btn btn-success">Create profile for Competetion</a>
    </div>
    </div>
{% endblock %}

fashionista/cool/templates/cool/register.html
{% extends 'cool/base_visitor.html' %}
{% block title %}Register{% endblock %}
{% block register_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'cool/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'cool:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


fashionista/cool/templates/cool/registration_form.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}